### ISSUE TITLE
Show tick mark every x step

### ISSUE THREAD

**Issue by WebTiger89** [hearsilent/DiscreteSlider#10]
Hi,
can you implement to show tick marks on, e.g. every 20 step. Currently when I set a tickMarkPattern  of "dot,dash" I get a tick mark on every single step so when I have a count of 250 I have 250 marks.
Thanks in advance!

**Comment by hearsilent** [comment]
Hi @WebTiger89 ,
Thanks for suggestion!
I'll add this feature in next version, maybe you can create PR ;)

**Comment by hearsilent** [comment]
Hi @WebTiger89 
I've support this feature in latest commit (#11)
You can try it from now!
