### ISSUE TITLE
AAPT: error: attribute ds_progressOffset not found.

### ISSUE THREAD

**Issue by IAmDarush** [hearsilent/DiscreteSlider#13]
I get this error when setting the progress offset attribute:

`AAPT: error: attribute ds_progressOffset (aka com.example.android:ds_progressOffset) not found.`

I am using this version:
`implementation 'com.github.hearsilent:DiscreteSlider:1.1.2'`

**Comment by hearsilent** [comment]
@IAmDarush Sorry for that, It's in develop stage, will release new version soon.

**Comment by IAmDarush** [comment]
@hearsilent thank you for your great effort. It's a great library. 

I would also like to request a feature. Right now `OnValueChangedListener.onValueChanged()` is called only after the slider thumb is released. It would be great if there was a way to receive slider values during sliding i.e. as soon as the slider value is changed.

**Comment by hearsilent** [comment]
@IAmDarush I've released new version 1.2.0, you can try now.
New version can `setValueChangedImmediately` to fire `onValueChanged` as soon as the slider value is changed.

Enjoy it!
