### ISSUE TITLE
Feature Request: range slider thumbs should be able to cross each other

### ISSUE THREAD

**Issue by IAmDarush** [hearsilent/DiscreteSlider#14]
Hi, Thank you for your great library.

I have used the Google material slider component and found that each thumb can be dragged from minProgress up to maxProgress and they can pass through each other. 

You can see the behavior in the following GIF:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22366924/78864763-e67a7e00-7a6e-11ea-975e-0326d0dd7d6e.gif)

Currently, in range mode, the min and max value thumbs cannot be dragged past each other.

**Comment by hearsilent** [comment]
@IAmDarush Sorry, I don't think the min and max value thumbs can be dragged past each other.
