### ISSUE TITLE
Setting the maximum progress value

### ISSUE THREAD

**Issue by ingeniousgenius** [hearsilent/DiscreteSlider#15]
How can you set the largest possible progress value on the slider? For example if I wanted the range to be between 0 and 250, or 1 and 14 how can that be done?

I assumed calling:

```java
slider.setMinProgress(0)
slider.setMaxProgress(250)
````

but that didn't work.

**Comment by ingeniousgenius** [comment]
What is the purpose of the "count" property?

**Comment by hearsilent** [comment]
@jesster2k10 `count` is used for slider total count, if you set count to 250, then range will be 0 to 249.
`minProgress` and `maxProgress` is current progress of silder.

If you want the range to be 1 to 14, you can set progress offset to `1` and count to `14`.
