### ISSUE TITLE
How to change start and end value of 1-10 to 80-175 ?

### ISSUE THREAD

**Issue by raghavkishan** [hearsilent/DiscreteSlider#16]
@hearsilent how do I go about setting the lowest value as 80 and highest as 175. I tried using these mSlider.setMinProgress(5);
mSlider.setMaxProgress(10); 
but no luck.

**Comment by hearsilent** [comment]
Hi @raghavkishan,
you can use `setProgressOffset` to fix your start point 😉

**Comment by raghavkishan** [comment]
Thank you. That helps.
