### ISSUE TITLE
Listeners and nullability

### ISSUE THREAD

**Issue by pcostadev** [hearsilent/DiscreteSlider#2]
Hi,

Nice work in here. Just a few suggestions: split the listeners in two different ones for range mode and normal mode. If I only pretend to use normal code, boilerplate code is gonna be everywhere. Also, annotate your interface. I checked your code and it isn't. For people using Kotlin, the code generator will understand it as a possible null. 

Again, nice work. I'll probably gonna use it in my apps.

**Comment by hearsilent** [comment]
In 1.0.2 has added nullable annotate to listener.
The listener is not abstract, you can only override which you want :)

**Comment by pcostadev** [comment]
Indeed. Forgot about it
