### ISSUE TITLE
Add `fromUser` value for OnValueChangedListener

### ISSUE THREAD

**Issue by raylee4204** [hearsilent/DiscreteSlider#6]
Similar to the progress bar, it'd be nice to know if the value is changed from user input or not

**Comment by hearsilent** [comment]
@raylee4204 I'll try to implement it. Thanks for suggestion :)

**Comment by hearsilent** [comment]
@raylee4204 Sorry for being late. It's now support from `v1.1.1`. Try it!

**Comment by raylee4204** [comment]
@hearsilent Thanks!

It'd be great if you start including changelogs for each release, especially this release has a breaking change

**Comment by hearsilent** [comment]
@raylee4204 
Thx for suggestion!
I'll add changelog in future.
