### ISSUE TITLE
Swiping on the slider without touching the thumb doesn't update the displayed progress

### ISSUE THREAD

**Issue by teapack** [hearsilent/DiscreteSlider#7]
When I swipe on the slider (without touching the thumb), the progress is correctly changed (the `onValueChanged(int progress, boolean fromUser)` method is called), but the progress doesn't update (the thumb doesn't move).

To replicate this, set progress for example to 0, count to for example 10 and call `mSlider.setClickable(true);`. Then start swiping from e. g. 3 (or any value but 0 (any value but the one where the thumb currently is)) to e. g. 6. The `onValueChanged(int progress, boolean fromUser)` method is called correctly (with `progress` variable being 6 and `fromUser` being true), but the thumb doesn't move and the active track stays at 0. This happens every time when you start swiping from anywhere where the thumb isn't.

A workaround is calling `mSlider.setProgress(progress);` in `onValueChanged(int progress, boolean fromUser)`, but that breaks animations.

**Comment by hearsilent** [comment]
Hi @teapack,
I think can't swipe slider without touching the thumb.
So it's a bug, I've fixed listener trigger in wrong time issue.

You can update version to `1.1.2`.

**Comment by teapack** [comment]
Ok, `1.1.2` fixes it by removing that feature.

Is there any chance you'll add that back? You can swipe slider without touching the thumb on both `SeekBar` and `AppCompatSeekBar`, and I'm sure people are using that feature quite often. For example, when I'm changing volume/brightness on my phone, I always start sliding from _anywhere_ - I don't usually aim for the thumb.

**Comment by hearsilent** [comment]
I'll add this feature to next version.
Thx for suggestion!

**Comment by teapack** [comment]
Glad to hear that, thanks a lot!

**Comment by hearsilent** [comment]
@teapack I've released new version 1.2.0, you can try now!
